### ISSUE TITLE
Return 200 and an empty JSON object ({}) for DELETE rest calls

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/rocc-schemas#42]
https://swagger.io/docs/specification/describing-responses/

![image](https://user-images.githubusercontent.com/10556275/103610169-6f6d0a00-4f5a-11eb-8030-46189540cdb0.png)

Unless you want a response body for deleting things.

**Comment by tschaffter** [comment]
@thomasyu888

> A successful response of DELETE requests SHOULD be HTTP response code 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has been queued, or 204 (No Content) if the action has been performed but the response does not include an entity.

[Source](https://restfulapi.net/http-methods/#delete)

We are currently returning the entity deleted so 200 is the correct code. 204 would be if we decide to not return this entity.

Looking at [Google Healthcare API for deleting datasets](https://cloud.google.com/healthcare/docs/how-tos/datasets#api_4), they return an empty JSON object (`{}`). It's not clear from the doc but they should return the code 200 along with the empty JSON object because curl does not show `{}` when returning 204 AND an entity (I tried).

From a performance perspective, it's preferable to not return the entity deleted. The larger the entity, the more time the DELETE request would take to complete and the higher the load on the service. Therefore, I recommend to not return the entity deleted until we meet a use case that needs it. But since a simple GET before DELETE could be used, I don't think that there is an absolute need to return the entity with DELETE.

Now trying to understand why Google returns 200 + `{}` instead of 204 and no payload... I like the idea of systematically using 200 (OK) and an empty JSON object, in part to be compliant with 200 and to know that a JSON parser can always be applied on the returned payload. The smaller number of status code we rely on the simpler the server and client implementation would be.

## Proposal

- No longer return the entity deleted
- Return 200 + `{}` OR 204 and nothing

@thomasyu888 @vpchung Thoughts?

**Comment by vpchung** [comment]
I'm in favor of not returning anything (or an empty json object), as this was what I've done with my previous projects.

**Comment by thomasyu888** [comment]
I am also in favor of not returning anything, but have no strong preference as to whether we should use 200 + {} or 204

**Comment by tschaffter** [comment]
Great! I like the approach adopted by Google (Google + `{}`) because it makes the documentation *more structured*. 

## Google approach (preferred)

ALL documentation pages look like:

- "The body of the input request looks like this:"

```
<example of request body>
```

- "The response payload looks like this:"

```
<example of response payload>
```

## Approach where both 200 and 204 exist at the level of the API

SOME pages (endpoints) have their doc formatted as above (Google style) and SOME pages have their doc formatted as shown below:

- "The body of the input request looks like this:"

```
<example of request body>
```

- "There is no output"

**Comment by tschaffter** [comment]
@vpchung Can you please create a PR that updates the schema so that delete operation return 200 and an empty JSON object (`{}`).

**Comment by thomasyu888** [comment]
Renamed issue for clarity.
