### ISSUE TITLE
Investigate the use of OpenAPI `links`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#49]
This feature could improve the quality of our OpenAPI documentation:
https://swagger.io/docs/specification/links/

**Comment by vpchung** [comment]
I played around with this feature by adding it to ` POST /challenges` and here are my findings:

* Adding the links themselves was very easy.  Similar to everything else, they can either be defined inline, e.g.

```
    '201':
      links:
        GetChallengeById:
          operationId: getChallenge
          description: >
            The `id` value returned in the response can be used as the
            `challengeId` parameter in `GET /challenges/{challengeId}`
          parameters:
            challengeId: $response.body#/challengeId
```

or globally under `components/links/`, e.g.

```
    '201':
      links:
        GetChallengeById:
          $ref: ../components/links/GetChallengeById.yaml
```

I tried it both ways but I think if we were to move forward with the links feature, they should be defined globally so that they are more easily reused.

* No change is seen in the schema documentation or client documentation, e.g.

<img width="540" alt="Screen Shot 2021-02-18 at 15 32 19" src="https://user-images.githubusercontent.com/9377970/108443823-54a2dc00-720e-11eb-880d-63fe9e22c65d.png">

At first, this confused me, so I thought maybe I had implemented the links incorrectly.  However, when I open the API spec documentation, information about the links _are_ seen:

<img width="540" alt="Screen Shot 2021-02-18 at 15 23 13" src="https://user-images.githubusercontent.com/9377970/108444018-aea3a180-720e-11eb-938b-92f8c5c1bda9.png">

Given all of this, I am not overly convinced that this will improve our documentation by much, at least, not with our current set of APIs.  In my opinion, they are straightforward enough already, i.e. it is fairly obvious that `challengeId` returned by `POST /challenges` can be used as the input for `GET /challenges/{challengeId}` and `DELETE /challenges/{challengeId}`.

What do you think, @tschaffter ?

**Comment by vpchung** [comment]
On second thought, after reading this [blog post](https://blog.readme.com/an-example-filled-guide-to-swagger-3-2/#linking), I can see why "linking" could be useful, specifically:

> Let’s say you get a user, and it has an `addressId`. This `addressId` is pretty useless by itself. You can use links to show how to “expand” that, and get the full address... In the response from "/users/{userId}", we get back an `addressId`. The "links" describes how we can get an address by referencing the "$response.body#/addressId".

Furthermore, they'll help with the cursor-based pagination, should we decide to move down that route.

I'm going to go ahead and start implementing this feature!
